//USER
export const FETCH_USER = 'FETCH_USER';

// PLAYLIST
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
export const FETCH_PLAYLISTS_FAILED = 'FETCH_PLAYLISTS_FAILED';
export const FETCH_PLAYLISTS_FULFILLED= 'FETCH_PLAYLISTS_FULFILLED';
export const FETCH_PLAYLISTS_PENDING = 'FETCH_PLAYLISTS_PENDING';

export const SEARCH_PLAYLISTS = 'SEARCH_PLAYLISTS';


export const FETCH_PLAYLIST_TRACKS = "FETCH_PLAYLIST_TRACKS";
export const FETCH_PLAYLIST_RANDOM = "FETCH_PLAYLIST_RANDOM";